/* 
 * $license$
 */

/*! @addtogroup bsx
 * @{
 */

#ifndef BSX_VIRTUAL_SENSOR_IDENTIFIER_H_
#define BSX_VIRTUAL_SENSOR_IDENTIFIER_H_

/*! @brief Provides the enumeration containing virtual sensor identifier 
 *
 * @{
 */ 
#define  BSX_VIRTUAL_SENSOR_ID_INVALID   (0)
#define BSX_OUTPUT_ID_ACCELERATION_PASSTHROUGH   (2)
#define BSX_CUSTOM_ID_ACCELERATION_PASSTHROUGH   (4)
#define BSX_OUTPUT_ID_ACCELERATION_RAW   (6)
#define BSX_OUTPUT_ID_ACCELERATION_CORRECTED   (8)
#define BSX_OUTPUT_ID_ACCELERATION_OFFSET   (10)
#define BSX_WAKEUP_ID_ACCELERATION_OFFSET   (182)
#define BSX_WAKEUP_ID_ACCELERATION_CORRECTED   (12)
#define BSX_WAKEUP_ID_ACCELERATION_RAW   (14)
#define BSX_CUSTOM_ID_ACCELERATION_CORRECTED   (16)
#define BSX_CUSTOM_ID_ACCELERATION_RAW   (18)
#define BSX_OUTPUT_ID_ANGULARRATE_PASSTHROUGH   (20)
#define BSX_CUSTOM_ID_ANGULARRATE_PASSTHROUGH   (22)
#define BSX_OUTPUT_ID_ANGULARRATE_RAW   (24)
#define BSX_OUTPUT_ID_ANGULARRATE_CORRECTED   (26)
#define BSX_OUTPUT_ID_ANGULARRATE_OFFSET   (28)
#define BSX_WAKEUP_ID_ANGULARRATE_OFFSET   (184)
#define BSX_WAKEUP_ID_ANGULARRATE_CORRECTED   (30)
#define BSX_WAKEUP_ID_ANGULARRATE_RAW   (32)
#define BSX_CUSTOM_ID_ANGULARRATE_CORRECTED   (34)
#define BSX_CUSTOM_ID_ANGULARRATE_RAW   (36)
#define BSX_OUTPUT_ID_MAGNETICFIELD_PASSTHROUGH   (38)
#define BSX_CUSTOM_ID_MAGNETICFIELD_PASSTHROUGH   (40)
#define BSX_OUTPUT_ID_MAGNETICFIELD_RAW   (42)
#define BSX_OUTPUT_ID_MAGNETICFIELD_CORRECTED   (44)
#define BSX_OUTPUT_ID_MAGNETICFIELD_OFFSET   (46)
#define BSX_WAKEUP_ID_MAGNETICFIELD_OFFSET   (186)
#define BSX_WAKEUP_ID_MAGNETICFIELD_CORRECTED   (48)
#define BSX_WAKEUP_ID_MAGNETICFIELD_RAW   (50)
#define BSX_CUSTOM_ID_MAGNETICFIELD_CORRECTED   (52)
#define BSX_CUSTOM_ID_MAGNETICFIELD_RAW   (54)
#define BSX_OUTPUT_ID_GRAVITY   (56)
#define BSX_WAKEUP_ID_GRAVITY   (58)
#define BSX_CUSTOM_ID_GRAVITY   (60)
#define BSX_OUTPUT_ID_LINEARACCELERATION   (62)
#define BSX_WAKEUP_ID_LINEARACCELERATION   (64)
#define BSX_CUSTOM_ID_LINEARACCELERATION   (66)
/** @brief NDOF or e-Compass */
#define BSX_OUTPUT_ID_ROTATION   (68)
/** @brief NDOF or e-Compass */
#define BSX_WAKEUP_ID_ROTATION   (70)
#define BSX_CUSTOM_ID_ROTATION   (72)
/** @brief no magnetic field */
#define BSX_OUTPUT_ID_ROTATION_GAME   (74)
/** @brief no magnetic field */
#define BSX_WAKEUP_ID_ROTATION_GAME   (76)
#define BSX_CUSTOM_ID_ROTATION_GAME   (78)
/** @brief no gyroscope, only e-Compass */
#define BSX_OUTPUT_ID_ROTATION_GEOMAGNETIC   (80)
/** @brief no gyroscope, only e-Compass */
#define BSX_WAKEUP_ID_ROTATION_GEOMAGNETIC   (82)
#define BSX_CUSTOM_ID_ROTATION_GEOMAGNETIC   (84)
/** @brief deprecated: NDOF or e-Compass computed from OUTPUT_ROTATION */
#define BSX_OUTPUT_ID_ORIENTATION   (86)
/** @brief deprecated: NDOF or e-Compass computed from WAKEUP_ROTATION */
#define BSX_WAKEUP_ID_ORIENTATION   (88)
#define BSX_CUSTOM_ID_ORIENTATION   (90)
#define BSX_OUTPUT_ID_FLIP_STATUS   (92)
#define BSX_CUSTOM_ID_FLIP_STATUS   (94)
#define BSX_OUTPUT_ID_TILT_STATUS   (96)
#define BSX_CUSTOM_ID_TILT_STATUS   (98)
#define BSX_OUTPUT_ID_STEPDETECTOR   (100)
#define BSX_WAKEUP_ID_STEPDETECTOR   (188)
#define BSX_CUSTOM_ID_STEPDETECTOR   (102)
#define BSX_OUTPUT_ID_STEPCOUNTER   (104)
#define BSX_WAKEUP_ID_STEPCOUNTER   (106)
#define BSX_CUSTOM_ID_STEPCOUNTER   (108)
#define BSX_OUTPUT_ID_SIGNIFICANTMOTION_STATUS   (110)
#define BSX_CUSTOM_ID_SIGNIFICANTMOTION_STATUS   (112)
#define BSX_OUTPUT_ID_WAKE_STATUS   (114)
#define BSX_CUSTOM_ID_WAKE_STATUS   (116)
#define BSX_OUTPUT_ID_GLANCE_STATUS   (118)
#define BSX_CUSTOM_ID_GLANCE_STATUS   (120)
#define BSX_OUTPUT_ID_PICKUP_STATUS   (122)
#define BSX_CUSTOM_ID_PICKUP_STATUS   (124)
#define BSX_OUTPUT_ID_ACTIVITY   (126)
#define BSX_CUSTOM_ID_ACTIVITY   (128)
#define BSX_OUTPUT_ID_PROPAGATION   (130)
#define BSX_OUTPUT_ID_POSITION_STEPS   (132)
#define BSX_OUTPUT_ID_WRIST_TILT_STATUS   (134)
#define BSX_CUSTOM_ID_WRIST_TILT_STATUS   (136)
#define BSX_OUTPUT_ID_DEVICE_ORIENTATION   (138)
#define BSX_WAKEUP_ID_DEVICE_ORIENTATION   (140)
#define BSX_CUSTOM_ID_DEVICE_ORIENTATION   (142)
#define BSX_OUTPUT_ID_POSE_6DOF   (144)
#define BSX_WAKEUP_ID_POSE_6DOF   (146)
#define BSX_CUSTOM_ID_POSE_6DOF   (148)
#define BSX_OUTPUT_ID_STATIONARY_DETECT   (150)
#define BSX_CUSTOM_ID_STATIONARY_DETECT   (152)
#define BSX_OUTPUT_ID_MOTION_DETECT   (154)
#define BSX_CUSTOM_ID_MOTION_DETECT   (156)
#define BSX_OUTPUT_ID_STANDBY_STATUS   (158)
#define BSX_OUTPUT_ID_ACCELERATION_STATUS   (160)
#define BSX_OUTPUT_ID_ACCELERATION_DYNAMIC   (162)
#define BSX_OUTPUT_ID_ANGULARRATE_STATUS   (164)
#define BSX_OUTPUT_ID_MAGNETICFIELD_STATUS   (166)
/** @brief dedicated debug output for the angular rate from M4G */
#define BSX_OUTPUT_ID_ANGULARRATE_M4G   (168)
/** @brief dedicated debug output for the angular rate from M4G */
#define BSX_WAKEUP_ID_ANGULARRATE_M4G   (170)
/*!
 * @}
 */ 

#endif /* BSX_VIRTUAL_SENSOR_IDENTIFIER_H_ */

/*! @}
 */
